# Generated by Django 5.1.3 on 2024-11-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibroDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_titulo', models.CharField(db_column='titulo', max_length=200)),
                ('_autor', models.CharField(db_column='autor', max_length=100)),
                ('_anio_publicacion', models.DateField(db_column='anio_publicacion')),
                ('_formato', models.CharField(max_length=50)),
                ('_tamanio_mb', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LibroFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_titulo', models.CharField(db_column='titulo', max_length=200)),
                ('_autor', models.CharField(db_column='autor', max_length=100)),
                ('_anio_publicacion', models.DateField(db_column='anio_publicacion')),
                ('_num_paginas', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
