# Generated by Django 5.1.3 on 2024-11-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaBiblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librodigital',
            name='anio_publicacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='librofisico',
            name='anio_publicacion',
            field=models.DateField(),
        ),
    ]
